########## Main menu ##########

[[main]]
identifier = "approach"
name = "aanpak"
title = "aanpak"
url = "/nl/approach/"
pageRef = "/approach"
weight = 10
[[main]]
identifier = "solutions"
name = "oplossingen"
title = "oplossingen"
url = "/nl/solutions/"
pageRef = "/solutions"
weight = 20
	[[main]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "conversational ai"
	title = "conversational ai"
	url = "/nl/solutions/conversational-ai/"
	pageRef = "/solutions/conversational-ai"
	weight = 22
	[[main]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "intelligent document processing"
	title = "intelligent document processing"
	url = "/nl/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
	[[main]]
	identifier = "smartcall-assistance"
	parent = "solutions"
	name = "smart call assistance"
	title = "smart call assistance"
	url = "/nl/solutions/smartcall-assistance/"
	pageRef = "/solutions/smartcall-assistance"
	weight = 26
[[main]]
identifier = "services"
name = "diensten"
title = "diensten"
url = "/nl/services/"
pageRef = "/services"
weight = 30
[[main]]
identifier = "company"
name = "bedrijf"
title = "bedrijf"
url = "/nl/company/"
pageRef = "/company"
weight = 40
	[[main]]
	identifier = "careers"
	parent = "company"
	name = "carrière"
	title = "carrière"
	url = "/nl/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[main]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "kennisbank"
	title = "kennisbank"
	url = "/nl/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[main]]
	identifier = "faq"
	parent = "company"
	name = "veelgestelde vragen"
	title = "veelgestelde vragen"
	url = "/nl/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[main]]
identifier = "contact"
name = "contact"
title = "contact"
url = "/nl/contact/"
pageRef = "/contact"
weight = 50



########## Footer menu ##########

[[footer]]
identifier = "home"
name = "Home"
url = "/nl/"
pageRef = "/"
weight = 1

[[footer]]
identifier = "approach"
name = "Aanpak"
url = "/nl/approach/"
pageRef = "/approach"
weight = 10
[[footer]]
identifier = "solutions"
name = "Oplossingen"
url = "/nl/solutions/"
pageRef = "/solutions"
weight = 20
	[[footer]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "Conversational AI"
	url = "/nl/solutions/conversational-ai/"
	pageRef = "/solutions/conversational-ai"
	weight = 22
	[[footer]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "Intelligent Document Processing"
	url = "/nl/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
	[[footer]]
	identifier = "smartcall-assistance"
	parent = "solutions"
	name = "Smart Call Assistance"
	url = "/nl/solutions/smartcall-assistance/"
	pageRef = "/solutions/smartcall-assistance"
	weight = 26
[[footer]]
identifier = "services"
name = "Diensten"
url = "/nl/services/"
pageRef = "/services"
weight = 30
[[footer]]
identifier = "company"
name = "Bedrijf"
url = "/nl/company/"
pageRef = "/company"
weight = 40
	[[footer]]
	identifier = "careers"
	parent = "company"
	name = "Carrière"
	url = "/nl/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[footer]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "Kennisbank"
	url = "/nl/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[footer]]
	identifier = "faq"
	parent = "company"
	name = "Veelgestelde vragen"
	url = "/nl/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[footer]]
identifier = "contact"
name = "Contact"
url = "/nl/contact/"
pageRef = "/contact"
weight = 50
